from enum import Enum


class City(str, Enum):
    """
    UK cities
    """

    bath = "bath"
    birmingham = "birmingham"
    bradford = "bradford"
    brighton_hove = "brighton & hove"
    bristol = "bristol"
    cambridge = "cambridge"
    canterbury = "canterbury"
    carlisle = "carlisle"
    chelmsford = "chelmsford"
    chester = "chester"
    chichester = "chichester"
    colchester = "colchester"
    coventry = "coventry"
    derby = "derby"
    doncaster = "doncaster"
    durham = "durham"
    ely = "ely"
    exeter = "exeter"
    gloucester = "gloucester"
    hereford = "hereford"
    kingston_upon_hull = "kingston-upon-hull"
    lancaster = "lancaster"
    leeds = "leeds"
    leicester = "leicester"
    lichfield = "lichfield"
    lincoln = "lincoln"
    liverpool = "liverpool"
    london = "london"
    manchester = "manchester"
    milton_keynes = "milton keynes"
    newcastle_upon_tyne = "newcastle-upon-tyne"
    norwich = "norwich"
    nottingham = "nottingham"
    oxford = "oxford"
    peterborough = "peterborough"
    plymouth = "plymouth"
    portsmouth = "portsmouth"
    preston = "preston"
    ripon = "ripon"
    salford = "salford"
    salisbury = "salisbury"
    sheffield = "sheffield"
    southampton = "southampton"
    southend_on_sea = "southend-on-sea"
    st_albans = "st albans"
    stoke_on_trent = "stoke on trent"
    sunderland = "sunderland"
    truro = "truro"
    wakefield = "wakefield"
    wells = "wells"
    westminster = "westminster"
    winchester = "winchester"
    wolverhampton = "wolverhampton"
    worcester = "worcester"
    york = "york"
    armagh = "armagh"
    bangor = "bangor"
    belfast = "belfast"
    lisburn = "lisburn"
    londonderry = "londonderry"
    newry = "newry"
    aberdeen = "aberdeen"
    dundee = "dundee"
    dunfermline = "dunfermline"
    edinburgh = "edinburgh"
    glasgow = "glasgow"
    inverness = "inverness"
    perth = "perth"
    stirling = "stirling"
    cardiff = "cardiff"
    newport = "newport"
    st_asaph = "st asaph"
    st_davids = "st davids"
    swansea = "swansea"
    wrexham = "wrexham"
    douglas = "douglas"
    hamilton = "hamilton"
    city_of_gibraltar = "city of gibraltar"
    stanley = "stanley"
    jamestown = "jamestown"
